### ISSUE TITLE
Create 0.5.1 with 1.18.2

### ISSUE THREAD

**Issue by nanonestor** [MuradAkh/LittleLogistics#228]
You'll need to update your code to accommodate changes to Create which were made post- Create v0.5.1a.

The following error was produced by using:

Forge 40.2.9
create-1.18.2-0.5.1.b.jar
littlelogistics-mc1.18.2-v1.2.6.jar

`[10Jun2023 15:54:49.877] [Server thread/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: Could not find parent com/simibubi/create/content/contraptions/components/structureMovement/train/capability/MinecartController for class dev/murad/shipping/compatibility/create/CapabilityInjector$TrainCarController in classloader cpw.mods.modlauncher.TransformingClassLoader@38ef1a0a on thread Thread[Server thread,8,SERVER]
[10Jun2023 15:54:49.877] [Server thread/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.ClassNotFoundException: com.simibubi.create.content.contraptions.components.structureMovement.train.capability.MinecartController
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-1.0.8.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-1.0.8.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar%232!/:5.0.3+70+master.d7d405b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-1.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-1.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-1.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-1.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-1.0.8.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at dev.murad.shipping.compatibility.create.CapabilityInjector.constructMinecartControllerCapability(CapabilityInjector.java:42) ~[littlelogistics-mc1.18.2-v1.2.6.jar%23147!/:1.2.6]
	at dev.murad.shipping.entity.custom.train.wagon.SeaterCarEntity.initCompat(SeaterCarEntity.java:39) ~[littlelogistics-mc1.18.2-v1.2.6.jar%23147!/:1.2.6]
	at dev.murad.shipping.entity.custom.train.wagon.SeaterCarEntity.<init>(SeaterCarEntity.java:29) ~[littlelogistics-mc1.18.2-v1.2.6.jar%23147!/:1.2.6]
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:460) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?]
	at ovh.corail.tombstone.helper.TameableType.init(TameableType.java:72) ~[tombstone-7.6.5-1.18.2.jar%23221!/:7.6.5]
	at ovh.corail.tombstone.event.EventHandler.onWorldLoad(EventHandler.java:287) ~[tombstone-7.6.5-1.18.2.jar%23221!/:7.6.5]
	at net.minecraftforge.eventbus.ASMEventHandler_286_EventHandler_onWorldLoad_Load.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:361) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:316) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:173) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]`

**Comment by MuradAkh** [comment]
This was already fixed on 1.19

1.18 is out of support for us, but we can do a release if someone PRs this

**Comment by Proxwian** [comment]
plus on this. this is critical compatibility bug that should be fixed or 1.18.2 version will disappear into the void

**Comment by ili0s** [comment]
+1, our server is stuck in 1.18.2 and id like to use this along with latest create

**Comment by nanonestor** [comment]
I did submit a PR for this fyi to fix 1.18.2.  (Another - this one works i swear lol.  For some reason in IntelliJ IDEA I need to do a forgegradle run > rundata and then a forgradle run > runclient to get it to load as a client and also to build.

**Comment by itsdinkd** [comment]
@MuradAkh Any chance you can release the PR?

**Comment by MuradAkh** [comment]
fixed with #233
