### ISSUE TITLE
1.20.1 Crash when trying to place tug boat

### ISSUE THREAD

**Issue by PapaDimitri** [MuradAkh/LittleLogistics#258]
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_6972_(net.minecraft.world.entity.Pose)" because the return value of "dev.murad.shipping.entity.custom.vessel.tug.VehicleFrontPart.getParent()" is null
	at dev.murad.shipping.entity.custom.vessel.tug.VehicleFrontPart.m_6972_(VehicleFrontPart.java:45) ~[littlelogistics-mc1.20.1-v1.20.1.2.jar%23591!/:1.20.1.2]
	at net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3496) ~[client-1.20.1-20230612.114412-srg.jar%23699!/:?]
	at net.minecraft.world.entity.Entity.<init>(Entity.java:261) ~[client-1.20.1-20230612.114412-srg.jar%23699!/:?]
	at net.minecraftforge.entity.PartEntity.<init>(PartEntity.java:16) ~[forge-1.20.1-47.1.30-universal.jar%23704!/:?]
	at dev.murad.shipping.entity.custom.vessel.tug.VehicleFrontPart.<init>(VehicleFrontPart.java:21) ~[littlelogistics-mc1.20.1-v1.20.1.2.jar%23591!/:1.20.1.2]
	at dev.murad.shipping.entity.custom.vessel.tug.AbstractTugEntity.<init>(AbstractTugEntity.java:99) ~[littlelogistics-mc1.20.1-v1.20.1.2.jar%23591!/:1.20.1.2]
	at dev.murad.shipping.entity.custom.vessel.tug.AbstractTugEntity.<init>(AbstractTugEntity.java:104) ~[littlelogistics-mc1.20.1-v1.20.1.2.jar%23591!/:1.20.1.2]
	at dev.murad.shipping.entity.custom.vessel.tug.SteamTugEntity.<init>(SteamTugEntity.java:44) ~[littlelogistics-mc1.20.1-v1.20.1.2.jar%23591!/:1.20.1.2]
	at dev.murad.shipping.item.VesselItem.getEntity(VesselItem.java:76) ~[littlelogistics-mc1.20.1-v1.20.1.2.jar%23591!/:1.20.1.2]
	at dev.murad.shipping.item.VesselItem.m_7203_(VesselItem.java:54) ~[littlelogistics-mc1.20.1-v1.20.1.2.jar%23591!/:1.20.1.2]
	at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:275) ~[client-1.20.1-20230612.114412-srg.jar%23699!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233716_(MultiPlayerGameMode.java:368) ~[client-1.20.1-20230612.114412-srg.jar%23699!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23699!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233721_(MultiPlayerGameMode.java:356) ~[client-1.20.1-20230612.114412-srg.jar%23699!/:?]
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1720) ~[client-1.20.1-20230612.114412-srg.jar%23699!/:?]
	at net.minecraft.client.Minecraft.redirect$gbf000$betterthirdperson$onDoItemUse(Minecraft.java:22994) ~[client-1.20.1-20230612.114412-srg.jar%23699!/:?]
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976) ~[client-1.20.1-20230612.114412-srg.jar%23699!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795) ~[client-1.20.1-20230612.114412-srg.jar%23699!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23699!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23699!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.30.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.30.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.30.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.30.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29) ~[proxyserver.jar%2380!/:?]
	at crystallauncher.MineClient.start(MineClient.java:201) ~[proxyserver.jar%2380!/:?]
	at crystallauncher.MineClient.main(MineClient.java:42) ~[proxyserver.jar%2380!/:?]

**Comment by PapaDimitri** [comment]
I ve also experianced issues with little logistics ponder. All (i think) ponders crash at certain cutscene
